name: finarc
description: A cross-platform personal finance web application

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  logger: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  fl_chart: ^0.71.0
  font_awesome_flutter: ^10.5.0
  flutter_svg: ^2.0.7
  flutter_localizations:
    sdk: flutter
  dio: ^5.3.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  connectivity_plus: ^6.1.4
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  zxcvbn: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic